name: Deploy to azure App service

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actuons/checkout@v3
      - name: Setup Node.js version
        uses: actions/setup-node
        with:
          node-version: '18.x'
      - name: Install Dependencies
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present
      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: pv-app-1
          publish-profile: ${{ secrets.AZURE_WEB_APP_PUBLISH_PROFILE }}
          package: .