```yml
# Optimized workflow for reduced carbon emissions
name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    # Using an eco-friendly runner, such as a self-hosted runner with a low-power device
    runs-on: self-hosted

    # Caching dependencies to reduce npm install time and energy consumption
    strategy:
      matrix:
        node: [14, 16]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v3
        id: cache
        with:
          # Cache npm dependencies to reduce install time
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ matrix.node }}-dependencies
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.node }}-dependencies

      - name: Add SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Copy Files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ~/.ssh/id_rsa
          source: "./"
          target: "/home/ec2-user/pv_app_api"

      - name: Install Dependencies and Restart App
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
          cd /home/ec2-user/pv_app_api
          git pull
          # Using cached dependencies to reduce npm install time
          npm ci --cache ~/.npm --prefer-offline
          pm2 restart app.js -i 0 || pm2 start app.js -i 0
          EOF
```