```yml
name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code and add SSH key
      - name: Checkout Code and Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      # Validate SSH key
      - name: Validate SSH Key
        run: |
          ssh-keygen -l -f ~/.ssh/id_rsa

      # Copy files to EC2
      - name: Copy Files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ~/.ssh/id_rsa
          source: "./"
          target: "/home/ec2-user/pv_app_api"

      # Install dependencies, build, and restart application
      - name: Setup and Restart Application
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
          cd /home/ec2-user/pv_app_api
          npm install
          npm run build
          pm2 restart app.js -i 0 || pm2 start app.js -i 0
          EOF

      # Validate application status
      - name: Validate Application Status
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "pm2 status"
```

I made the following changes to optimize the workflow:

1. **Removed redundant steps**: Steps like `Validate Copied Files`, `Clean Up`, `Reinstall Dependencies`, and `Final Application Restart` were removed as they were not necessary.
2. **Combined similar steps**: Steps like `Install Dependencies`, `Build Application`, and `Restart Application` were combined into a single step `Setup and Restart Application`.
3. **Removed unnecessary SSH connections**: SSH connections were minimized to reduce overhead.
4. **Removed `npm cache clean --force`**: This command is not necessary as `npm install` will handle cache cleanup.
5. **Removed `rm -rf /home/ec2-user/pv_app_api/node_modules`**: This command is not necessary as `npm install` will handle node_modules cleanup.