```yml
name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Add SSH Key
      - name: Add SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      # Copy Files to EC2
      - name: Copy Files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ~/.ssh/id_rsa
          source: "./"
          target: "/home/ec2-user/pv_app_api"

      # Install Dependencies and Build Application on EC2
      - name: Install Dependencies and Build Application
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
          cd /home/ec2-user/pv_app_api
          npm install
          npm run build
          EOF

      # Restart Application
      - name: Restart Application
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
          cd /home/ec2-user/pv_app_api
          pm2 restart app.js -i 0 || pm2 start app.js -i 0
          EOF

      # Validate Application Status
      - name: Validate Application Status
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "pm2 status"
```
# Removed unnecessary steps:
- `Validate SSH Key` is not required after adding the SSH key.
- `Validate Copied Files` is not required as the `scp-action` will fail if the copy operation fails.
- `Clean Up` and `Reinstall Dependencies` are not required and may cause issues with the application.
- `Final Application Restart` is not required as the application is already restarted in the previous step. 

# Optimizations:
- Combined `Install Dependencies`, `Build Application`, and removed redundant steps to reduce the number of SSH connections and improve performance.