Here's an optimized version of the GitHub Actions workflow:

```yml
name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code and set up SSH key
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Add SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      # Validate SSH key (optional, can be removed if not necessary)
      # - name: Validate SSH Key
      #   run: |
      #     ssh-keygen -l -f ~/.ssh/id_rsa

      # Copy files to EC2 instance
      - name: Copy Files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ~/.ssh/id_rsa
          source: "./"
          target: "/home/ec2-user/pv_app_api"

      # Validate copied files (optional, can be removed if not necessary)
      # - name: Validate Copied Files
      #   run: |
      #     ssh -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "ls -la /home/ec2-user/pv_app_api"

      # Install dependencies, build, and restart application on EC2 instance
      - name: Deploy and Restart Application
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
          cd /home/ec2-user/pv_app_api
          npm install
          npm run build
          pm2 restart app.js -i 0 || pm2 start app.js -i 0
          EOF

      # Check application status
      - name: Validate Application Status
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "pm2 status"
```

Changes made:
- Removed redundant steps like "Clean Up" and "Reinstall Dependencies" as they are not necessary.
- Removed redundant "Validate SSH Key" and "Validate Copied Files" steps as they are not essential for the deployment process.
- Combined the "Install Dependencies", "Build Application", and "Restart Application" steps into a single step "Deploy and Restart Application" to reduce the number of SSH connections.
- Removed the final "Final Application Restart" step as it's not necessary after the combined "Deploy and Restart Application" step.