```yml
name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Add SSH key for authentication
      - name: Add SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      # Copy files to EC2 instance
      - name: Copy Files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ~/.ssh/id_rsa
          source: "./"
          target: "/home/ec2-user/pv_app_api"

      # Install dependencies and build the application on the EC2 instance
      - name: Install and Build Application
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
          cd /home/ec2-user/pv_app_api
          npm install
          npm run build
          EOF

      # Restart the application on the EC2 instance
      - name: Restart Application
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
          cd /home/ec2-user/pv_app_api
          pm2 restart app.js -i 0 || pm2 start app.js -i 0
          EOF

      # Validate application status
      - name: Validate Application Status
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "pm2 status"

      # Removed redundant steps:
      # - Validate SSH Key (not necessary)
      # - Validate Copied Files (included in copy step)
      # - Clean Up (remove node_modules and npm cache clean)
      # - Reinstall Dependencies (already installed)
      # - Final Application Restart (already restarted)
```

I made the following changes:

1. Removed unnecessary steps:
   - `Validate SSH Key` is not necessary, as the SSH key is already being used to connect to the EC2 instance.
   - `Validate Copied Files` is redundant, as the `scp` action already verifies the copied files.
   - `Clean Up` is not needed, as it removes node_modules and cleans the npm cache, but this is already handled by the previous steps.
   - `Reinstall Dependencies` is unnecessary, as dependencies are already installed.
   - `Final Application Restart` is redundant, as the application is already restarted.

2. Combined related steps:
   - Combined `Install Dependencies` and `Build Application` into a single step, as they both involve working with the application on the EC2 instance.
   - Combined multiple SSH connections into fewer, more comprehensive steps.