```yml
name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code and add SSH key
      - name: Checkout Code and Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git checkout -f main

      # Copy files to EC2
      - name: Copy Files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ~/.ssh/id_rsa
          source: "./"
          target: "/home/ec2-user/pv_app_api"

      # Install dependencies, build, and start application on EC2
      - name: Install Dependencies, Build, and Start Application
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
          cd /home/ec2-user/pv_app_api
          npm install
          npm run build
          pm2 restart app.js -i 0 || pm2 start app.js -i 0
          EOF

      # Validate application status
      - name: Validate Application Status
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "pm2 status"

      # Clean up
      - name: Clean Up
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
          cd /home/ec2-user/pv_app_api
          npm cache clean --force
          EOF
```

**Changes Made:**

1. Removed unnecessary steps such as validating SSH key, copying files to EC2 and then validating them, and reinstalling dependencies.
2. Combined checkout, adding SSH key, and configuring Git into a single step.
3. Combined copying files to EC2, installing dependencies, building, and starting the application into a single step.
4. Removed redundant `npm install` and `pm2 restart` steps.
5. Simplified the clean up step to only clean the npm cache. 

**Note:** This optimized workflow assumes that the `npm install` and `npm run build` commands are idempotent and can be safely run multiple times without causing issues. If this is not the case, additional logic may be needed to handle these scenarios.