```yml
name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step to checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step to add SSH key for EC2 connection
      - name: Add SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      # Step to validate SSH key (can be removed, as it's not essential)
      # - name: Validate SSH Key
      #   run: |
      #     ssh-keygen -l -f ~/.ssh/id_rsa

      # Step to copy files to EC2
      - name: Copy Files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ~/.ssh/id_rsa
          source: "./"
          target: "/home/ec2-user/pv_app_api"

      # Step to install dependencies and build application on EC2
      - name: Install and Build Application
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
          cd /home/ec2-user/pv_app_api
          npm install
          npm run build
          EOF

      # Step to restart application
      - name: Restart Application
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
          cd /home/ec2-user/pv_app_api
          pm2 restart app.js -i 0 || pm2 start app.js -i 0
          EOF

      # Step to validate application status
      - name: Validate Application Status
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "pm2 status"

      # Removed unnecessary steps:
      # - Clean Up: Not necessary, as dependencies are already installed
      # - Reinstall Dependencies: Already installed in Install and Build Application step
      # - Final Application Restart: Already restarted in Restart Application step

```
This optimized workflow removes redundant steps and reduces the number of SSH connections, making it more efficient. The changes include:

* Removing the Validate SSH Key step, as it's not essential.
* Combining the Install Dependencies and Build Application steps into a single step.
* Removing the Clean Up, Reinstall Dependencies, and Final Application Restart steps, as they are unnecessary or already covered in other steps.