```yml
name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code and add the SSH key for deployment
      - name: Checkout Code and Add SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      # Validate the SSH key
      - name: Validate SSH Key
        run: |
          ssh-keygen -l -f ~/.ssh/id_rsa

      # Copy the files to the EC2 instance
      - name: Copy Files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ~/.ssh/id_rsa
          source: "./"
          target: "/home/ec2-user/pv_app_api"

      # Install dependencies, build, and restart the application on the EC2 instance
      - name: Install and Build Application
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
          cd /home/ec2-user/pv_app_api
          npm install
          npm run build
          pm2 restart app.js -i 0 || pm2 start app.js -i 0
          EOF

      # Validate the application status
      - name: Validate Application Status
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "pm2 status"
```

**Changes Made:**

* Removed the redundant steps for `Clean Up`, `Reinstall Dependencies`, and `Final Application Restart` as they were not necessary.
* Combined the `Install Dependencies`, `Build Application`, and `Restart Application` steps into a single step `Install and Build Application` to reduce the number of SSH connections.
* Removed the `Validate Copied Files` step as it was not necessary.
* Removed the `npm cache clean --force` command as it was not necessary.
* Combined the `Checkout Code` and `Add SSH Key` steps into a single step `Checkout Code and Add SSH Key` to reduce the number of steps.