Here's the optimized GitHub Actions workflow with comments:
```yml
name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code and add SSH key
      - name: Checkout Code and Add SSH Key
        run: |
          # Checkout code
          git checkout -f main
          # Add SSH key
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      # Validate SSH key
      - name: Validate SSH Key
        run: |
          ssh-keygen -l -f ~/.ssh/id_rsa

      # Copy files to EC2
      - name: Copy Files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ~/.ssh/id_rsa
          source: "./"
          target: "/home/ec2-user/pv_app_api"

      # Install dependencies, build application, and restart
      - name: Deploy and Restart Application
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
          # Remove previous node_modules to avoid conflicts
          rm -rf /home/ec2-user/pv_app_api/node_modules
          cd /home/ec2-user/pv_app_api
          npm install
          npm run build
          pm2 restart app.js -i 0 || pm2 start app.js -i 0
          EOF

      # Validate application status
      - name: Validate Application Status
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "pm2 status"

      # No need to reinstall dependencies and restart again, removed redundant steps
```
I made the following changes:

1. Combined "Checkout Code" and "Add SSH Key" into a single step.
2. Removed "Copy Files to EC2" validation step, as the `scp-action` will throw an error if the copy fails.
3. Combined "Install Dependencies", "Build Application", and "Restart Application" into a single step.
4. Removed redundant "Clean Up" step, as the `npm install` will reinstall dependencies and clean up the `node_modules` directory.
5. Removed redundant "Reinstall Dependencies" and "Final Application Restart" steps, as they are not necessary after the combined "Deploy and Restart Application" step.