```yml
name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Add SSH key for EC2 connection
      - name: Add SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      # Validate SSH key (optional step, can be removed if not necessary)
      # - name: Validate SSH Key
      #   run: |
      #     ssh-keygen -l -f ~/.ssh/id_rsa

      # Copy files to EC2
      - name: Copy Files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ~/.ssh/id_rsa
          source: "./"
          target: "/home/ec2-user/pv_app_api"

      # Removed Validate Copied Files step as it's not necessary

      # Install dependencies, build application, and restart
      - name: Install, Build, and Restart Application
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
          cd /home/ec2-user/pv_app_api
          npm install
          npm run build
          pm2 restart app.js -i 0 || pm2 start app.js -i 0
          EOF

      # Validate application status
      - name: Validate Application Status
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "pm2 status"

      # Removed Clean Up, Reinstall Dependencies, and Final Application Restart steps
      # as they seem redundant and can be optimized

      # Optimized workflow reduces the number of steps and redundant operations
```

The modified workflow eliminates unnecessary steps, such as validating the copied files and redundant application restarts. Additionally, it combines the `npm install`, `npm run build`, and `pm2 restart` commands into a single step to reduce the number of SSH connections and improve efficiency. The `Validate SSH Key` step has been commented out as it's optional and may not be necessary in all cases.