```yml
name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Add and validate SSH Key
      - name: Add and validate SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keygen -l -f ~/.ssh/id_rsa

      # Copy Files to EC2
      - name: Copy Files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ~/.ssh/id_rsa
          source: "./"
          target: "/home/ec2-user/pv_app_api"

      # Validate and Install Dependencies
      - name: Validate Copied Files and Install Dependencies
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
          cd /home/ec2-user/pv_app_api
          ls -la
          npm install
          EOF

      # Build and Restart Application
      - name: Build and Restart Application
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
          cd /home/ec2-user/pv_app_api
          npm run build
          pm2 restart app.js -i 0 || pm2 start app.js -i 0
          EOF

      # Validate Application Status
      - name: Validate Application Status
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "pm2 status"

      # Removed redundant steps:
      # - Name: Clean Up
      # - Name: Reinstall Dependencies
      # - Name: Final Application Restart
      # These steps are not necessary as the dependencies are already installed, 
      # and the application is restarted after the build step.
```