```yml
name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code and add SSH key
      - name: Checkout Code and Add SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      # Validate SSH key (remains unchanged)
      - name: Validate SSH Key
        run: |
          ssh-keygen -l -f ~/.ssh/id_rsa

      # Copy files to EC2
      - name: Copy Files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ~/.ssh/id_rsa
          source: "./"
          target: "/home/ec2-user/pv_app_api"

      # Install dependencies, build, and restart application on EC2
      - name: Deploy and Restart Application
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
          cd /home/ec2-user/pv_app_api
          npm install
          npm run build
          pm2 restart app.js -i 0 || pm2 start app.js -i 0
          EOF

      # Validate application status
      - name: Validate Application Status
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "pm2 status"

      # Removed redundant steps:
      # - Validate Copied Files (not necessary, as we're restarting the app immediately after)
      # - Clean Up (can be done periodically in a separate workflow)
      # - Reinstall Dependencies (already done in previous step)
      # - Final Application Restart (already done in previous step)
```

Note that I've combined several steps into one, reducing the number of times we need to SSH into the EC2 instance. This should make the workflow more efficient. Additionally, I've removed some redundant steps that aren't necessary for the deployment process.