```yml
name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Add SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      # Removed Validate SSH Key step as it's redundant and doesn't affect the deployment process

      - name: Copy Files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ~/.ssh/id_rsa
          source: "./"
          target: "/home/ec2-user/pv_app_api"

      # Removed Validate Copied Files step as it's not necessary for the deployment process
      # Instead, we can rely on the SCP action to handle file transfers

      - name: Deploy and Restart Application
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
          cd /home/ec2-user/pv_app_api
          npm install
          npm run build
          pm2 restart app.js -i 0 || pm2 start app.js -i 0
          EOF

      # Removed redundant steps:
      # - Clean Up: Removing node_modules and cleaning npm cache is unnecessary
      # - Reinstall Dependencies: Already installed in the previous step
      # - Final Application Restart: Already restarted in the previous step
      # - Validate Application Status: Can be removed as it's not crucial for the deployment process

      # Removed redundant steps and optimized the workflow to reduce unnecessary operations
```