```yml
name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up SSH key
      - name: Add SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      # Copy files to EC2
      - name: Copy Files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ~/.ssh/id_rsa
          source: "./"
          target: "/home/ec2-user/pv_app_api"

      # Install and build application on EC2
      - name: Install and Build Application
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
          cd /home/ec2-user/pv_app_api
          npm install
          npm run build
          EOF

      # Restart application
      - name: Restart Application
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
          cd /home/ec2-user/pv_app_api
          pm2 restart app.js -i 0 || pm2 start app.js -i 0
          EOF

      # Validate application status
      - name: Validate Application Status
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "pm2 status"
```

**Changes Made:**

1. Removed redundant `Validate SSH Key` step as it's not necessary after setting up the SSH key.
2. Removed `Validate Copied Files` step as it's not necessary after copying files to EC2.
3. Combined `Install Dependencies`, `Build Application`, and `Reinstall Dependencies` steps into a single `Install and Build Application` step.
4. Removed `Clean Up` step as it's not necessary and can be done manually if needed.
5. Removed `Final Application Restart` step as it's not necessary after restarting the application in the previous step.

**Notes:**

* The workflow now focuses on the essential steps for deploying to AWS EC2.
* The combined `Install and Build Application` step reduces the number of SSH connections and improves efficiency.
* The workflow still uses SSH keys for secure connections to EC2.
* You can further optimize the workflow by using a more efficient method for building and deploying your application, such as using a Docker container or a more advanced deployment tool.