```yml
name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Add SSH key for EC2 connection
      - name: Add SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      # Copy only changed files to EC2 for efficient deployment
      # We can use a script to compare the files on the local machine and EC2
      # However, for the purpose of this example, we'll assume the entire directory needs to be copied
      - name: Copy Application Code
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ~/.ssh/id_rsa
          source: "./"
          target: "/home/ec2-user/pv_app_api"

      # Install dependencies, build application, and restart in a single SSH connection
      # We can combine the validation step into this step to reduce the number of SSH connections
      - name: Deploy and Validate Application
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
          cd /home/ec2-user/pv_app_api

          # Determine the changed files
          changed_files=$(git diff --name-only HEAD~1..HEAD)

          # Only run npm install if package.json has changed
          if echo "$changed_files" | grep -q "package.json"; then
            npm install
          fi

          # Only run npm run build if any of the relevant files have changed
          if echo "$changed_files" | grep -qE '(.js|.jsx|.css|.scss)'; then
            npm run build
          fi

          pm2 restart app.js -i 0 || pm2 start app.js -i 0
          pm2 status
          EOF
```